### ISSUE TITLE
Stretching of multiple gradients

### ISSUE THREAD

**Issue by joesavage** [davatron5000/deCSS3#16]
After hearing about deCSS3 on ShopTalk I decided to take a look.
It's working great, however I have run into a little but which I figured I'd report (sorry if this sounds a little bit ramble-y for a GitHub issue, but I don't submit many of these things).

Basically when using the bookmarklet on pages of my site, the background (which consists of multiple gradients) screws up and stretches. This is illustrated perfectly when going to http://www.dev-hq.net/ and activating then de-activating the bookmarklet - the background compresses together (I've tested in Chrome). It's interesting to note that when going on to different pages of my website, for example http://www.dev-hq.net/5, the gradient gets stretched the opposite way.

Sorry I couldn't be more helpful and give some sort of test case in which I've found it screws up or find the root of the issue, but I'm a little pushed for time.

**Comment by SlexAxton** [comment]
I haven't been in this code in a while, but I'd bet this comes from
improperly wiping out comma delimited values.

If people are actually using this now, perhaps its time to fix that one.

Thanks!

**Comment by davatron5000** [comment]
Thanks for the feedback. As of right now, we don't have full support for stripping out `linear-gradient` and no support for multiple backgrounds.  So it's probably all these combining together. The stretch you're seeing is probably the loss of `background-size` in some capacity. FWIW, it appears to be working just great on later versions of Chrome: http://cl.ly/3s2r3r2D1r0x45260k3d

I'm going to close this issue for right now, since we don't quite support these features yet, but when we do and if its still broke we can reopen.  Thanks again.

**Comment by SlexAxton** [comment]
That's what I meant...

**Comment by joesavage** [comment]
"That's what I meant..." - Hah :P
"FWIW, it appears to be working just great on later versions of Chrome" - Yeah, the stripping works great for me in Chrome too - it's just the un-strip after that which screws up the background.

"I'm going to close this issue for right now, since we don't quite support these features yet, but when we do and if its still broke we can reopen" - Ok, makes sense - thanks!
