### ISSUE TITLE
toggling issue

### ISSUE THREAD

**Issue by lawrencetaur** [davatron5000/deCSS3#19]
when i try this out on a page with css3 by clicking on the bookmark, it does degrade gracefully, but i expected it to get back to css3 when i click it again,

things which happen, 
- icon fonts disappear
- flex slider(which was disabled using display:none) appears again. 
- it doesn't degrade radial gradients, but i'm sure this is an issue you are working on. 

On the whole, a great job. very useful tool and encourages me to use modernizr even more. 

Browser: Chrome 16
OS: Windows 7

**Comment by davatron5000** [comment]
I'd need to see what page you're referring to because it could be code specific... but here's my assumptions:
- We strip out `:before` & `:after` - that's probably affecting your icon fonts.
- No idea about flexslider.
- We don't support radial gradients as outlined in our [Feature Roadmap Matrix in the Cloud](https://github.com/davatron5000/deCSS3/blob/master/readme.md).
